# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
executors:
  php-72:
    docker:
      - image: thecodingmachine/php:7.2-v2-cli
jobs:
  install-and-self-analyse:
    executor: php-72
    steps:
      - checkout
      - run: date "+%F" > /tmp/cachekey; cat composer.json >> /tmp/cachekey
      - restore_cache:
          keys:
            - composer-v2-{{ checksum "/tmp/cachekey" }}
            # fallback to using the latest cache if no exact match is found (See https://circleci.com/docs/2.0/caching/)
            - composer-v2-
      - run: composer update
      - save_cache:
          key: composer-v2-{{ checksum "/tmp/cachekey" }}
          paths:
            - vendor
      - run:
          name: Static analysis
          command: php -dextension=pcntl.so ./psalm --threads=10
      - persist_to_workspace:
          root: /home/docker/project/
          paths:
            - .
  "Code Style Analysis":
    executor: php-72
    steps:
      - attach_workspace:
          at: /home/docker/project/
      - run:
          name: Code Style Analysis with PHPCS
          command: vendor/bin/phpcs
  test:
    executor: php-72
    steps:
      - attach_workspace:
          at: /home/docker/project/
      - run:
          name: PHPUnit test
          command: php vendor/bin/phpunit --log-junit build/phpunit/phpunit.xml
      - store_test_results:
          path: build/
      - store_artifacts:
          path: build/phpunit
      - persist_to_workspace:
          root: /home/docker/project/
          paths:
            - .
  coverage:
    executor: php-72
    steps:
      - attach_workspace:
          at: /home/docker/project/
      - run:
          name: PHPUnit test with coverage
          command: php -dextension=pcov.so vendor/bin/phpunit --log-junit build/phpunit/phpunit.xml --coverage-xml build/phpunit/coverage-xml --coverage-html build/phpunit/coverage-html
      - store_artifacts:
          path: build/phpunit
      - persist_to_workspace:
          root: /home/docker/project/
          paths:
            - .
  mutation:
    executor: php-72
    steps:
      - attach_workspace:
          at: /home/docker/project/
      - run:
          name: Install infection
          command: composer global require infection/infection
      - run:
          name: Mutation coverage testing
          command: |
            set -e;
            set -x;
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              CHANGED_FILES=$(git diff --name-only $(git log -1 --before=@{1.month.ago}  --format=%H) --stat | grep "^src") || { echo 'no source files changed; not running infection'; exit};
              echo 'This is master, so running muation testing for any files changed in last month';
            else
              CHANGED_FILES=$(git diff --name-only HEAD $(git merge-base HEAD origin/master) | grep "^src/") || { echo 'no source files changed; not running infection'; exit};
              INFECTION_FILTER="--filter=${CHANGED_FILES} --ignore-msi-with-no-mutations";
              echo "Running mutation testing only for files changed on branch ${CIRCLE_BRANCH}";
            fi

            # the test below uses composer and the install script for ocramius/package-versions would cause an error here.
            mv tests/EndToEnd/PsalmEndToEndTest.php tests/EndToEnd/PsalmEndToEndTest.php.skipped

            echo 'Only running mutations for the following files files:'
            echo ${CHANGED_FILES} | tr " " "\n"

            php -d memory_limit=4G ~/.composer/vendor/bin/infection --coverage=build/phpunit --only-covered --threads=2 $INFECTION_FILTER
  phar-build:
    executor: php-72
    steps:
      - attach_workspace:
          at: /home/docker/project/
      - run:
          name: Build Phar file
          command: bin/build-phar.sh
      - run:
          name: Smoke test Phar file
          command: build/psalm.phar --version
      - store_artifacts:
          path: build/psalm.phar
      - persist_to_workspace:
          root: /home/docker/project/
          paths:
            - build/psalm.phar
  test-with-real-projects:
    executor: php-72
    steps:
      - checkout # used here just for the side effect of loading the github public ssh key so we can clone other stuff
      - attach_workspace:
          at: /home/docker/project/
      - run:
          name: Analyse PHPUnit
          command: bin/test-with-real-projects.sh
      - store_artifacts:
          path: build/psalm.phar

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  Welcome:
    jobs:
      - install-and-self-analyse
      - test:
          requires:
            - install-and-self-analyse
      - "Code Style Analysis":
          requires:
            - install-and-self-analyse
      - coverage:
          requires:
            - test
            - "Code Style Analysis"
      - mutation:
          requires:
            - coverage
      - phar-build:
          requires:
            - test
            - "Code Style Analysis"
      - test-with-real-projects:
          requires:
            - phar-build
